eventuality/events/urls.py
from django.urls import path

from .views import (
    AttendEventView,
    CreateEventView,
    DeleteEventView,
    DetailEventView,
    ListEventsView,
    UpdateEventView,
    WithdrawFromEventView,
)

app_name = "events"
urlpatterns = [
    path("", ListEventsView.as_view(), name="list"),
    path("create", CreateEventView.as_view(), name="create"),
    path("<int:event_id>", DetailEventView.as_view(), name="detail"),
    path("<int:event_id>/update", UpdateEventView.as_view(), name="update"),
    path("<int:event_id>/delete", DeleteEventView.as_view(), name="delete"),
    path("<int:event_id>/attend", AttendEventView.as_view(), name="attend"),
    path("<int:event_id>/withdraw", WithdrawFromEventView.as_view(), name="withdraw"),
]

eventuality/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic.base import RedirectView

from eventuality.users.views import RegisterView

urlpatterns = [
    path("", RedirectView.as_view(url="/events/"), name="home"),
    path("events/", include("eventuality.events.urls")),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="registration/logout.html"), name="logout"),
]

eventuality/events/models.py
from django.db import models
from django.urls import reverse

import humanize

from eventuality.users.models import User
from eventuality.utils.abstract import UpdatableModel


class Event(UpdatableModel):
    class Meta:
        verbose_name = "event"
        verbose_name_plural = "events"
        db_table = "events"

    title = models.CharField("title", max_length=255)
    description = models.TextField("description", null=True, blank=True)
    starts_at = models.DateTimeField("starts", db_index=True)
    ends_at = models.DateTimeField("ends", db_index=True)
    canceled_at = models.DateTimeField("canceled", null=True, blank=True, db_index=True)
    created_by = models.ForeignKey(User, db_index=True, on_delete=models.CASCADE)
    attendees = models.ManyToManyField(to=User, through="events.EventAttendee", related_name="events")

    def get_absolute_url(self):
        return reverse("events:detail", kwargs={"event_id": self.pk})

    @property
    def duration(self):
        return humanize.naturaldelta(self.ends_at - self.starts_at)


class EventAttendee(UpdatableModel):
    """
    The only reason to have a separate table for this many-to-many is to have the `created_at` and `updated_at` fields
    managed by the database. This isn't required by the application, but future us will be happy if we ever want this
    data for any reason, including audit purposes.

    Note that we enforce a `unique_together` on this table, but the views may do some magic to make this invisible to
    the user just for UX purposes.
    """

    class Meta:
        verbose_name = "event attendee"
        verbose_name_plural = "event attendees"
        db_table = "event_attendees"
        unique_together = [
            ["event", "user"],
        ]

    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

eventuality/events/forms.py
import datetime

from django.forms import ModelForm
from django.forms.fields import SplitDateTimeField
from django.forms.widgets import SplitDateTimeWidget
from django.utils import timezone

from .models import Event


class EventForm(ModelForm):
    """
    The view could handle this fine, but we want to provide some semblance of usability
    with this form, so we'll override the default widget to use date type.
    """

    class Meta:
        model = Event
        fields = ["title", "starts_at", "ends_at", "description"]

    starts_at = SplitDateTimeField(
        initial=lambda: timezone.now(),
        widget=SplitDateTimeWidget(date_attrs={"type": "date"}, time_attrs={"type": "time"},),
    )
    ends_at = SplitDateTimeField(
        initial=lambda: timezone.now() + datetime.timedelta(minutes=30),
        widget=SplitDateTimeWidget(date_attrs={"type": "date"}, time_attrs={"type": "time"},),
    )

eventuality/events/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import Count, OuterRef, Prefetch, Q, Subquery
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, View

from eventuality.users.models import User

from .forms import EventForm
from .models import Event, EventAttendee


class ListEventsView(LoginRequiredMixin, ListView):
    model = Event
    template_name = "events/list.html"
    paginate_by = 20
    ordering = ["starts_at"]

    def get_queryset(self, *args, **kwargs):
        now = timezone.now()
        # so the acceptance criteria is to sort with upcoming events first, this means past events
        # aren't as important, I guess? We'll filter it this way:
        # 1. if an event is currently in progress, we'll show it
        #    (i.e. starts_at is less than now, but ends_at is in the future)
        # 2. if an event is upcoming (starts_at is in the future), we'll show it
        qs = (
            super()
            .get_queryset(*args, **kwargs)
            .filter(Q(starts_at__gt=now) | Q(Q(starts_at__lt=now) & Q(ends_at__gt=now)))
        )

        # we'll return an Event, but we're also interested in how many attendees.
        # let's _not_ make the template layer hit the database to get that and "prefetch" it.

        # When this was initially built, the page would take 5(!) seconds to load if I had
        # events with more than 1000 attendees. I couldn't let that stand.
        # So I threw together a subquery. This gave me the sql I wanted... except for
        # one little "GROUP BY" that django insisted it needed buecase of the annotate.
        attendees_queryset = (
            EventAttendee.objects.filter(
                # use the event id from the url
                event_id=OuterRef("id"),
            )
            .annotate(count=Count("id"))
            .order_by()
            .values("count")
        )
        # so I murdered it. right here.
        attendees_queryset.query.group_by = []

        # get my subquery that does the counts of attendees without creating a left outer join
        subquery = Subquery(attendees_queryset)
        qs = (
            qs.select_related("created_by")
            # uses all that above so that instead of 5 second page load, we have ~60ms
            .annotate(attendee_count=subquery)
        )
        return qs


class DetailEventView(LoginRequiredMixin, DetailView):
    model = Event
    template_name = "events/detail.html"
    pk_url_kwarg = "event_id"
    attendees_queryset = None
    # we're going to paginate the attendees because there could be thousands, per specifications
    paginator = None
    paginate_by = 20

    def get_queryset(self):
        qs = super().get_queryset()
        # pagination on a many to many is interesting in django. if we were doing this in pure
        # sql, we'd just do some subquery stuff magics.... So we have to replicate that thinking
        # in django.
        page_number = self.request.GET.get("page", 1)
        self.attendees_queryset = (
            # subquery the attendees (this won't actually hit the database, but design some sql)
            EventAttendee.objects.filter(
                # use the event id from the url
                event_id=self.kwargs.get(self.pk_url_kwarg)
            ).annotate(count=Count("user_id"))
            # this order by needs to match the users prefetch below in order to provide
            # consistent pagination
            .order_by("user__email")
        )

        self.paginator = Paginator(self.attendees_queryset, self.paginate_by)
        current_page = self.paginator.get_page(page_number)

        # subtract 1 because these are 1-based indexes
        start = current_page.start_index() - 1 if current_page.start_index() > 0 else 0
        end = current_page.end_index()
        print("start", start)
        subquery = Subquery(
            self.attendees_queryset
            # we'll doing a "where user in" type of query so we just need the user id
            .values_list("user_id")
            # limit this based on the paginator page
            # this is where the magical pagination stuff happens that makes this query
            # a little bigger, but faster
            [start:end]
        )

        qs = qs.select_related("created_by").prefetch_related(
            # design our own prefetch, where the users are in the paginated subquery above
            Prefetch("attendees", queryset=User.objects.filter(id__in=subquery).order_by("email"))
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        page_number = self.request.GET.get("page", 1)
        context["page_obj"] = self.paginator.get_page(page_number)
        return context


class CreateEventView(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventForm
    template_name = "events/create.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class UpdateEventView(LoginRequiredMixin, UpdateView):
    model = Event
    form_class = EventForm
    template_name = "events/update.html"
    pk_url_kwarg = "event_id"

    def get_object(self):
        event = super().get_object()
        if self.request.user != event.created_by:
            raise PermissionDenied
        return event


class DeleteEventView(LoginRequiredMixin, DeleteView):
    model = Event
    pk_url_kwarg = "event_id"

    def get_success_url(self):
        return reverse("events:list")

    def get_object(self):
        event = super().get_object()
        if self.request.user != event.created_by:
            raise PermissionDenied
        return event

    def post(self, request, event_id):
        event = self.get_object()
        event.canceled_at = timezone.now()
        # remove the attendees because the event is canceled
        event.attendees.all().delete()
        event.save()
        print("canceled")
        return HttpResponseRedirect(redirect_to=self.get_success_url())


class AttendEventView(LoginRequiredMixin, View):
    """
    This view breaks away from Django's CRUD view pattern a bit.
    We'll never actually show anything from the join table/model, and querying and
    serializing an event with all its bits is just absurd.

    1. we'll check that it's an actual event. users _do_ need to know if it's not a bogus event.
    2. we just add an entry into the EventAttendee table and redirect to the event detail.

    One thing that's especially unique is that this won't show an integrity error if
    the attendee is already joined. We just redirect them to the event. This, in theory,
    would reduce support calls for a confused user that thinks they got an error when
    trying to join an event they already have (if this were a real app).
    """

    pk_url_kwarg = "event_id"

    def post(self, request, event_id):
        # the logged in user can join any event, but they can never join an event for
        # someone else. So even if they, by some hackery, try to inject a user other
        # than themselves, we'll still join _them_ to the event
        event = Event.objects.filter(pk=event_id).only("canceled_at").first()
        if event is None:
            raise Http404

        if event.canceled_at is not None:
            # this event has been canceled, let the user know
            messages.error(request, "You are unable to attend this event due to it being canceled by the owner.")
            return HttpResponseRedirect(reverse("events:detail", kwargs={"event_id": event_id}))

        try:
            with transaction.atomic():
                try:
                    user = self.request.user
                    attendee = EventAttendee(user=user, event_id=event_id,)
                    attendee.save()
                except IntegrityError:
                    # rollback the transaction and act like nothing happened.
                    # the user is already a part of the event or the event didn't exist
                    transaction.rollback()
        except Exception:
            # if there's another type of error, we want to throw it in messages and still
            # redirect to the detail view for them to see.
            messages.error(request, "There was an error adding you to the event.")

        return HttpResponseRedirect(reverse("events:detail", kwargs={"event_id": event_id}))


class WithdrawFromEventView(LoginRequiredMixin, View):
    """
    This view follows the same pattern as AttendEventView, but with the opposite expectation:
    i.e. users are removed from the event. If they are not a part of the event we fail silently just like
    attending multiple times does.
    """

    pk_url_kwarg = "event_id"

    def post(self, request, event_id):
        # the logged in user can join any event, but they can never join an event for
        # someone else. So even if they, by some hackery, try to inject a user other
        # than themselves, we'll still join _them_ to the event
        exists = Event.objects.filter(pk=event_id).exists()
        if not exists:
            raise Http404

        try:
            with transaction.atomic():
                try:
                    user = self.request.user
                    EventAttendee.objects.filter(user=user, event_id=event_id).delete()
                except IntegrityError:
                    # rollback the transaction and act like nothing happened.
                    # the user is already a part of the event or the event didn't exist
                    transaction.rollback()

assets/templates/events/create.html
{% extends "base.html" %}

{% block "main" %}
<h1>Create Event</h1>

<div class="events__control">
    <a href="{% url 'events:list'%}">Back To Events</a>
</div>
<hr/>
<div class="events__editor">
  <form action="{% url 'events:create' %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" value="Create">
      <a class="btn btn-secondary" href="{% url 'events:list'%}">Cancel</a>
  </form>
</div>

{% endblock %}

assets/templates/events/detail.html
{% extends "base.html" %}
{% load tz %}

{% block "main" %}
<h1>Event: "{{object.title}}"</h1>

<div class="events__control">
    <a href="{% url 'events:list'%}">Back To Events</a>
    |
    <a href="{% url 'events:create'%}">Schedule a New Event</a>
</div>
<hr/>
<div class="event__detail">
    <h2>{{event.title}}</h2>
    <div class="row p-3">
      <div class="col-3">Created By:</div>
      <div class="col-3">
        {{event.created_by.public_name}}
        {% if event.created_by == user %}
        (you) - <a href="{% url 'events:update' event_id=event.id %}">Edit</a>
        {% endif %}
      </div>
    </div>
    <div class="row p-3">
      <div class="col-3">Starts:</div>
      <div class="col-3"><time>{{ event.starts_at }}</time></div>
    </div>
    <div class="row p-3">
      <div class="col-3">Ends:</div>
      <div class="col-3"><time>{{ event.ends_at }}</time></div>
    </div>
    <div class="row p-3">
      <div class="col-3">Duration:</div>
      <div class="col-3"><time>{{ event.duration }}</time></div>
    </div>
    <div class="row p-3">
      <div class="col-12"><time>{{ event.description }}</time></div>
    </div>
    <hr />
    <div class="attendees">
      <h3>Attendees</h3>
      <div class="attendees__pagination col-10 offset-1">
        {% if page_obj.has_other_pages %}
        <ul class="pagination small">
          {% if page_obj.has_previous %}
          <li class="col-4 text-left"><a href="?page={{ page_obj.previous_page_number }}">Previous {{ page_obj.per_page }}</a></li>
          {% endif %}
          <li class="col-4 text-center"><span>{{ page_obj.start_index }} - {{ page_obj.end_index }} of {{ page_obj.paginator.count }} attendees</span></li>
          {% if page_obj.has_next %}
          <li class="col-4 text-right"><a href="?page={{ page_obj.next_page_number }}">Next {{ page_obj.per_page }}</a></li>
          {% endif %}
        </ul>
        {% endif %}
      </div>
      <div class="attendees__item container">
        <div class="row">
          {# for attendee in page_obj.object_list #}
          {% for attendee in event.attendees.all %}
          <div class="col-3 p-2 text-center">{{ attendee.public_name }}</div>
          {% endfor %}
        </div>
      </div>
    </div>
</div>

{% endblock %}

assets/templates/events/list.html
{% extends "base.html" %}
{% load tz %}

{% block "main" %}
<h1>Events</h1>

<div class="events__control">
    <a href="{% url 'events:create'%}">Schedule a New Event</a>
</div>
<hr/>
<div class="events__list">
    <div class="events__pagination col-6">
        {% if page_obj.has_other_pages %}
          <ul class="pagination small">
            {% if page_obj.has_previous %}
              <li class="col-4 text-left"><a href="?page={{ page_obj.previous_page_number }}">Previous Events</a></li>
            {% else %}
            <li class="col-4 text-left"><em>Past Events Are Hidden</em></li>
            {% endif %}
            <li class="col-4 text-center"><span>{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span></li>
            {% if page_obj.has_next %}
              <li class="col-4 text-right"><a href="?page={{ page_obj.next_page_number }}">More Events</a></li>
            {% else %}
              <li class="col-4 text-left"><em>No More Events</em></li>
            {% endif %}
          </ul>
        {% endif %}
    </div>

    {% for event in object_list %}
    <div class="event__item">
        <h5>{{event.title}}</h5>
        <time>{{ event.starts_at }}</time>
        —
        <time>{{ event.ends_at }}</time>
        <em>(duration: {{ event.duration }})</em>
        - {{ event.attendee_count }} attendees
        <div class="event__item__user">
            <cite>Created by: {{event.created_by.public_name}}</cite>
        </div>
        <br />
        {% if event.created_by == user %}
        <a href="{% url 'events:detail' event_id=event.id %}">View</a>
        |
        <a href="{% url 'events:update' event_id=event.id %}">Edit</a>
        {% endif %}
    </div>
    <hr />
    {% endfor %}
    
    <div class="events__pagination col-6">
        {% if page_obj.has_other_pages %}
          <ul class="pagination small">
            {% if page_obj.has_previous %}
              <li class="col-4 text-left"><a href="?page={{ page_obj.previous_page_number }}">Previous Events</a></li>
            {% else %}
              <li class="col-4 text-left"><em>No Previous Events</em></li>
            {% endif %}
            <li class="col-4 text-center"><span>{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span></li>
            {% if page_obj.has_next %}
              <li class="col-4 text-right"><a href="?page={{ page_obj.next_page_number }}">More Events</a></li>
            {% else %}
              <li class="col-4 text-left"><em>No More Events</em></li>
            {% endif %}
          </ul>
        {% endif %}
    </div>
</div>

{% endblock %}

assets/templates/events/update.html
{% extends "base.html" %}

{% block "main" %}
<h1>Create Event</h1>

<div class="events__control">
    <a href="{% url 'events:list'%}">Back To Events</a>
</div>
<hr/>
<div class="events__editor">
  <form action="{% url 'events:update' event_id=object.id %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" value="Update">
      <a class="btn btn-secondary" href="{% url 'events:list'%}">Cancel</a>
  </form>
</div>

{% endblock %}